// Consts

export const START_GET_ALL_CHARACTERS = 'START_GET_ALL_CHARACTERS';
export const SUCCESS_GET_ALL_CHARACTERS = 'SUCCESS_GET_ALL_CHARACTERS';
export const ERROR_GET_ALL_CHARACTERS = 'ERROR_GET_ALL_CHARACTERS';