// Rick & Morty
export const START_GET_ALL_RICK_AND_MORTY_CHARACTERS = 'START_GET_ALL_RICK_AND_MORTY_CHARACTERS';
export const SUCCESS_GET_ALL_RICK_AND_MORTY_CHARACTERS = 'SUCCESS_GET_ALL_RICK_AND_MORTY_CHARACTERS';
export const ERROR_GET_ALL_RICK_AND_MORTY_CHARACTERS = 'ERROR_GET_ALL_RICK_AND_MORTY_CHARACTERS';

// Futurama
export const START_GET_ALL_FUTURAMA_CHARACTERS = 'START_GET_ALL_FUTURAMA_CHARACTERS';
export const SUCCESS_GET_ALL_FUTURAMA_CHARACTERS = 'SUCCESS_GET_ALL_FUTURAMA_CHARACTERS';
export const ERROR_GET_ALL_FUTURAMA_CHARACTERS = 'ERROR_GET_ALL_FUTURAMA_CHARACTERS';
export const START_GET_FUTURAMA_CHARACTERS_BY_NAME = 'START_GET_FUTURAMA_CHARACTERS_BY_NAME';
export const SUCCESS_GET_FUTURAMA_CHARACTERS_BY_NAME = 'SUCCESS_GET_FUTURAMA_CHARACTERS_BY_NAME';
export const ERROR_GET_FUTURAMA_CHARACTERS_BY_NAME = 'ERROR_GET_FUTURAMA_CHARACTERS_BY_NAME';