// Rick & Morty
export const START_GET_ALL_RICK_AND_MORTY_CHARACTERS = 'START_GET_ALL_RICK_AND_MORTY_CHARACTERS';
export const SUCCESS_GET_ALL_RICK_AND_MORTY_CHARACTERS = 'SUCCESS_GET_ALL_RICK_AND_MORTY_CHARACTERS';
export const ERROR_GET_ALL_RICK_AND_MORTY_CHARACTERS = 'ERROR_GET_ALL_RICK_AND_MORTY_CHARACTERS';
export const START_GET_RICK_AND_MORTY_CHARACTER_BY_ID = 'START_GET_RICK_AND_MORTY_CHARACTER_BY_ID';
export const SUCCESS_GET_RICK_AND_MORTY_CHARACTER_BY_ID = 'SUCCESS_GET_RICK_AND_MORTY_CHARACTER_BY_ID';
export const ERROR_GET_RICK_AND_MORTY_CHARACTER_BY_ID = 'ERROR_GET_RICK_AND_MORTY_CHARACTER_BY_ID';

// Futurama
export const START_GET_ALL_FUTURAMA_CHARACTERS = 'START_GET_ALL_FUTURAMA_CHARACTERS';
export const SUCCESS_GET_ALL_FUTURAMA_CHARACTERS = 'SUCCESS_GET_ALL_FUTURAMA_CHARACTERS';
export const ERROR_GET_ALL_FUTURAMA_CHARACTERS = 'ERROR_GET_ALL_FUTURAMA_CHARACTERS';
export const START_GET_FUTURAMA_CHARACTERS_BY_NAME = 'START_GET_FUTURAMA_CHARACTERS_BY_NAME';
export const SUCCESS_GET_FUTURAMA_CHARACTERS_BY_NAME = 'SUCCESS_GET_FUTURAMA_CHARACTERS_BY_NAME';
export const ERROR_GET_FUTURAMA_CHARACTERS_BY_NAME = 'ERROR_GET_FUTURAMA_CHARACTERS_BY_NAME';

// Pokemon
export const START_GET_ALL_POKEMONS = 'START_GET_ALL_POKEMONS';
export const SUCCESS_GET_ALL_POKEMONS = 'SUCCESS_GET_ALL_POKEMONS';
export const ERROR_GET_ALL_POKEMONS = 'ERROR_GET_ALL_POKEMONS';
export const START_GET_POKEMON_BY_ID = 'START_GET_POKEMON_BY_ID';
export const SUCCESS_GET_POKEMON_BY_ID = 'SUCCESS_GET_POKEMON_BY_ID';
export const ERROR_GET_POKEMON_BY_ID = 'ERROR_GET_POKEMON_BY_ID';